### ISSUE TITLE
Ошибка с порядковыми числительными

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/MorphNumbers#13]
Подскажите, можно текущую дату склонять? хочу получить ВОСЬМОГО ноября

{{ now().timestamp()|timestamp_custom('%d') }} ==> 08

{{ now().timestamp()|timestamp_custom('%d')|format(morph='первого') }}  ==>  восемь первых

{{ now().timestamp()|timestamp_custom('%d')|format(morph='первого', as_ordinal=True) }}  ==> TypeError: '>=' not supported between instances of 'str' and 'int'

**Comment by KKnishev** [comment]
Проблема в том, что timestamp_custom по умолчанию во float, если явно задать int, то работает
{{ now().timestamp()|timestamp_custom('%d')|int|format(morph='первого', as_ordinal=True) }}  ==> восьмого

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/MorphNumbers/releases/tag/v1.4.0
