### ISSUE TITLE
Не склоняет значение переменной

### ISSUE THREAD

**Issue by WeslyG** [AlexxIT/MorphNumbers#14]
С обычным литералом все нормально (как строковым, так и числовым) а вот с expression что-то случилось, и просто отдает значение без формата. 
 
![image](https://user-images.githubusercontent.com/12625945/168422949-db9bdc1a-f330-4ce5-8699-48697bc04e44.png)

ha version = core-2022.5.4
python = 3.9.9

**Comment by AlexxIT** [comment]
Поправил в последней мастер-версии

**Comment by WeslyG** [comment]
![image](https://user-images.githubusercontent.com/12625945/168442963-bb11b6f9-f4c7-424a-86da-416c19cf03f6.png)
Все работает! Спасибо за оперативность!

**Comment by sneakythr0ws** [comment]
релиз будет?

**Comment by eratnik** [comment]
Home Assistant 2022.7.3
Supervisor 2022.07.0
ветка мастер - тоже не работает с переменными.
![2.png](https://user-images.githubusercontent.com/23414787/179725879-2066a8fb-8521-406d-ab2c-73b262a5b309.png)

**Comment by Spirituss** [comment]
Когда ждать апдейт?

**Comment by AlexxIT** [comment]
Выпустил релиз v1.3.0

**Comment by lonsdaleite** [comment]
@AlexxIT 
Home Assistant 2022.7.6. Поставил версию 1.3.0. Как не работало, так и не работает. Ни с константами, ни с переменными.

**Comment by lonsdaleite** [comment]
Обновился до 2022.8.1 - то же самое.
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/6382100/183288004-98b59011-04b3-4fac-83af-3b35c6c65028.png">

**Comment by AlexxIT** [comment]
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/511909/184536574-d2a9d8c5-0799-4ebc-9008-1b7242cd2de2.png">
Не могу подтвердить проблему. Home Assistant 2022.8.4, всё работает

**Comment by notabene00** [comment]
<img width="814" alt="Снимок экрана 2022-08-14 в 17 18 43" src="https://user-images.githubusercontent.com/9576189/184541223-2faeca01-35e9-4974-96a9-fbac0239cba4.png">
Yep, works like a charm
1.3.0/2022.08.3

**Comment by lonsdaleite** [comment]
@AlexxIT, пардон, тупанул. Видимо, после каких-то первых тестов, когда проблема еще была, я выключил интеграцию, а потом не включил обратно. Сейчас включил, и всё работает, спасибо!
