### ISSUE TITLE
no filter named 'numword'

### ISSUE THREAD

**Issue by g0dsha** [AlexxIT/MorphNumbers#2]
Home Assistant 0.108.6

Добавил в скрипт фильтр numword (скрипт в packages):
На улице температура {{ state_attr('weather.gismeteo_daily', 'temperature') | numword('градус', false) }}

и сейчас иногда получаю:

Invalid config for [script]: invalid template (TemplateAssertionError: no filter named 'numword') for dictionary value @ data['script']['tts_summary_weather']['sequence'][0]['data_template']['message'].
Из-за чего все скрипты отваливаются. Может morph_numbers: не успевает запуститься?

**Comment by AlexxIT** [comment]
Да, не успевает запуститься. Несколько пользователей жаловались. У себя я не могу повторить. Что-то такое есть в вашем конфиге, чего нет у меня. Сложно вслепую понять в чём проблема.

**Comment by AlexQuaken** [comment]
Та-же проблема на двух инстансах Invalid config for [script]: invalid template (TemplateAssertionError: no filter named 'numword') for dictionary value скрипты не работают, менял местам строки в конфиге но кажись, порядок загрузки от этого не меняется. Может есть идеи как побороть ?

**Comment by AlexxIT** [comment]
Пока нет идей как повторить :)

**Comment by AlexxIT** [comment]
Надеюсь поправил в последнем релизе. Название функции поменялось!
