### ISSUE TITLE
Обратное преобразование.

### ISSUE THREAD

**Issue by booroondook-eng** [AlexxIT/MorphNumbers#20]
Скажите, а можно ли сделать функцию обратного преобразования - из текста в число?
На, например, что-то вроде этого:
`{{ 'сто двадцать три'|format(morph='') }} => 123`
хотя бы для ограниченного диапазона (например, положительные цифры от 1 до 999).

**Comment by AlexxIT** [comment]
```
{{ "два миллиона четыреста тридцать пять"|format(morph='', reverse=true) }}
```

https://github.com/AlexxIT/MorphNumbers/releases/tag/v1.4.0
