### ISSUE TITLE
Обновление HA до версии 2023.6.0

### ISSUE THREAD

**Issue by SandDeath** [AlexxIT/MorphNumbers#22]
![Screenshot_20230608-091056](https://github.com/AlexxIT/MorphNumbers/assets/25662096/837f1558-b8b0-4325-b792-25d717a85e1f)
![Screenshot_20230608-091157](https://github.com/AlexxIT/MorphNumbers/assets/25662096/90151fac-2610-49e7-a5d9-1875ca2c2ba5)
![Screenshot_20230608-091204](https://github.com/AlexxIT/MorphNumbers/assets/25662096/7f0741a9-1b6a-44ab-a1f0-613338a3e783)

Дополнение не запускается после июньского обновления Home Assistant

**Comment by AlexxIT** [comment]
#19
