### ISSUE TITLE
Числа как 21, 31, 41 склоняет неверно

### ISSUE THREAD

**Issue by AlexQuaken** [AlexxIT/MorphNumbers#3]
Числа как 21, 31, 41 склоняет неверно
Как пример: "Сервер перезагружен, за {{ 31|round|format(morph='секунда') }}"
Вывод: "Сервер перезагружен, за тридцать одна секунда"

**Comment by AlexxIT** [comment]
```
Сервер перезагружен, за {{ 31|round|format(morph='секунду') }}

{{ 31|round|format(morph='секунда') }} - это целая вечность!
```

В morph желательно указывать фразу для цифры 1.

**Comment by wantsoftat** [comment]
Component error: morph_numbers - Integration 'morph_numbers' not found. 
После установки из репозитория HACS
