### ISSUE TITLE
Не стартует интеграция 

### ISSUE THREAD

**Issue by wantsoftat** [AlexxIT/MorphNumbers#4]
_Component error: morph_numbers - Integration 'morph_numbers' not found._
После установки из репозитория HACS

**Comment by sshalyminov** [comment]
Аналогично после апдейта на 2021.6.0

**Comment by sshalyminov** [comment]
Related to https://github.com/AlexxIT/MorphNumbers/pull/10

**Comment by BrainFixer** [comment]
> Аналогичная проблема после апдейта на 2021.6.0
> Переустановка не влияет

Та же проблема. Обновление 2021.6.1 проблему не решило.

**Comment by GigaVik** [comment]
Версия
core-2021.6.1
Не работает.

**Comment by AlexxIT** [comment]
Много лет утекло, сейчас, вероятно уже работает?

**Comment by BrainFixer** [comment]
Да, интеграция работает, спасибо большое. Правда теперь сломался сам HACS :)), но это уже совсем другая история.
