### ISSUE TITLE
Ha 0.115 и далее, компонент не работает

### ISSUE THREAD

**Issue by balonchiks** [AlexxIT/MorphNumbers#6]
Добрый день, проблема похожа на то что было в соседней ветке #5

Перезагружал и homeassistant и контейнер по 10 раз - так же ничего не работает.

вот как выглядит конфиг из примера:

```
{{ 1|format(morph='градус') }}
{{ 1|format(morph='задача') }}
{{ 1|format(morph='дерево') }}

{{ 2000435|format(morph='синее облако') }}

{{ 2|format(morph='запланированная задача', as_text=false) }}
{{ 5|format(morph='просроченная задача', as_text=false) }}

{{ 123|format(morph='') }}

{{ 0|format(morph='градус') }}
{{ -2|format(morph='градус') }}
```
```
1
1
1

2000435

2
5

123

0
-2
```

в логе совсем пусто. до перехода на версию 0.115 все прекрасно работало. не посмотрите в чём причина?

**Comment by AlexxIT** [comment]
#5

**Comment by balonchiks** [comment]
да, похоже что абсолютно тоже самое, только перезагружать и контэйнер и homeassistant внутри контейнера я уже устал - никак не помогает :(

**Comment by balonchiks** [comment]
обсуждение в #5
