### ISSUE TITLE
Дробные числа

### ISSUE THREAD

**Issue by Shulyaka** [AlexxIT/MorphNumbers#8]
Добрый день.

Возможно, стоит воспринимать это больше как feature request, но интеграция отбрасывает дробную часть, причём округление всегда в меньшую сторону.

`{{ 24.99|format(morph='градус') }} -> "двадцать четыре градуса"`

**Comment by AlexxIT** [comment]
Можно сделать правильное округление через `|round`. А произносить 22 целых, 99 сотых градуса... Ну такое... :)

**Comment by Shulyaka** [comment]
Согласен в данном конкретном примере, но в каких-то случаях дробные числа могут пригодиться

**Comment by dankarization** [comment]
+1, дробные числа иногда нужны

**Comment by AlexxIT** [comment]
Можно адекватные жизненные примеры? :)

**Comment by dankarization** [comment]
Да хотя бы произносить температуру с точностью одного знака после запятой. 22,99 никому не надо, а вот 22 22.5 и 23 достаточно отличаются друг от друга

**Comment by AlexxIT** [comment]
Ну "двадцать два с половиной" ещё как-то звучит. А в других случаях как быть?

**Comment by dankarization** [comment]
"Двадцать два и четыре", например, без "десятых". Тоже нормально

**Comment by AlexxIT** [comment]
"Двадцать два и четыре градуса". Не очень

**Comment by dankarization** [comment]
Да вроде нормально. Лучше чем никак 🤷‍♂️

**Comment by AlexxIT** [comment]
Нужно звать кого-нибудь из педагогического :)

```
два и один градус в зале
два и один градуса в зале
пять и один градус в зале
пять и один градусов в зале
пять и два градуса в зале
пять и пять градусов в зале
пять и одна десятая градуса в зале
пять и две десятых градуса в зале
пять и две десятые градуса в зале
пять и два десятых градуса в зале
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/MorphNumbers/releases/tag/v1.5.0

**Comment by dankarization** [comment]
Спасибо!
