### ISSUE TITLE
Работа с количеством лет (год/года/лет)...

### ISSUE THREAD

**Issue by Aldaran** [AlexxIT/MorphNumbers#9]
Неудачная работа с числительными связанная с количеством лет:
{{ 1|format(morph='лет', as_text=false) }}      =>   1 года
{{ 2|format(morph='лет', as_text=false) }}      =>   2 годов
{{ 10|format(morph='лет', as_text=false) }}    =>   10 годов

{{ 1|format(morph='год', as_text=false) }}      =>   1 год
{{ 2|format(morph='год', as_text=false) }}      =>   2 года
{{ 10|format(morph='год', as_text=false) }}    =>   10 годов

Вообще хотелось бы увидеть возможность самому выставлять склонения в ручную.. Пример (что я имею ввиду)..
{{ 10|format(morph='год', array('год', 'года', 'лет'), as_text=false) }}    =>   10 лет

Благодарю за хорошие модули.

**Comment by AlexxIT** [comment]
Добавлено в последний релиз
